---
output:
  html_document: default
  pdf_document: default
---
> library(readxl)
> Fatalities <- read_excel("Fatalities.xlsx")
> View(Fatalities)
> #I am attempting to create a descriptive statistics of the 'year' column
> summary(Fatalities$year)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1982    1983    1985    1985    1987    1988 
> #Next, I will be doing the 'miles' column
> summary(Fatalities$miles)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   4576    7183    7796    7891    8504   26148 
> #Finally, I will do the 'income' column
> summary(Fatalities$income)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   9514   12086   13763   13880   15175   22193 
> #Now, I will attempt to transform the 'year' column
> filter(Fatalities$year)
Error in filter(Fatalities$year) : 
  argument "filter" is missing, with no default
> install.packages(dplyr)
Error in install.packages : object 'dplyr' not found
> install.packages("dplyr")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/allex/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/dplyr_1.1.3.zip'
Content type 'application/zip' length 1553555 bytes (1.5 MB)
downloaded 1.5 MB

package ‘dplyr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\allex\AppData\Local\Temp\RtmpyoH12U\downloaded_packages
> filter(Fatalities$year)
Error in filter(Fatalities$year) : 
  argument "filter" is missing, with no default
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> filter(Fatalities$year)
Error in UseMethod("filter") : 
  no applicable method for 'filter' applied to an object of class "c('double', 'numeric')"
> filter(Fatalities, year == '1985')
# A tibble: 48 × 35
   rownames state  year spirits unemp income emppop beertax baptist mormon drinkage     dry youngdrivers
      <dbl> <chr> <dbl>   <dbl> <dbl>  <dbl>  <dbl>   <dbl>   <dbl>  <dbl>    <dbl>   <dbl>        <dbl>
 1        4 al     1985    1.28  8.90 11333.   55.3  1.65    30.3    0.376     19.7 23.6           0.211
 2       11 az     1985    1.86  6.5  13727.   58.6  0.381    3.76   4.66      21    0             0.188
 3       18 ar     1985    1.12  8.70 11149.   55.0  0.577   23.1    0.376     21   35.9           0.189
 4       25 ca     1985    1.97  7.20 16985.   61.3  0.0953   1.76   1.65      21    0             0.168
 5       32 co     1985    2.05  5.90 15570.   67.9  0.191    2.30   1.86      21    0.0749        0.192
 6       39 ct     1985    2.41  4.90 19312.   65.9  0.239    0.100  0.294     20.3  0.0802        0.179
 7       46 de     1985    2.55  5.30 15409.   63.6  0.154    0.700  0.200     21    0             0.183
 8       53 fl     1985    2.27  6    14761.   56.4  1.14     8.52   0.400     20    0             0.170
 9       60 ga     1985    1.93  6.5  13364.   61.7  2.42    23.9    0.469     19.2  0.433         0.195
10       67 id     1985    1.18  7.90 11460.   61.3  0.358    1.06  24.7       19    0             0.213
# ℹ 38 more rows
# ℹ 22 more variables: miles <dbl>, breath <chr>, jail <chr>, service <chr>, fatal <dbl>, nfatal <dbl>,
#   sfatal <dbl>, fatal1517 <dbl>, nfatal1517 <dbl>, fatal1820 <dbl>, nfatal1820 <dbl>, fatal2124 <dbl>,
#   nfatal2124 <dbl>, afatal <dbl>, pop <dbl>, pop1517 <dbl>, pop1820 <dbl>, pop2124 <dbl>,
#   milestot <dbl>, unempus <dbl>, emppopus <dbl>, gsp <dbl>
# ℹ Use `print(n = ...)` to see more rows
> # I had to install the dplyr package before using the filter transformation
> #Now i will attempt to do a histogram for the 'year' column
> Date <- Fatalities$year
> hist(Date)
> #Next, I will create a scatterplot of the same column
> plot(Date)
> #I will be changing the values since the code above did not result in a scatterplot
> plot(year,fatal)
Error: object 'year' not found
> Death <- Fatalities$fatal
> plot(Date,Death)



